const createWine = require("./create")
const deleteWine = require("./delete")
const deleteFromCave = require("./deleteFromCave")
const deleteMany = require("./deleteMany")
const addToCave = require("./addToCave")
const list = require("./list")
const rate = require("./rate")
const find = require("./find")
const update = require("./update")

exports.createWine = createWine
exports.deleteWine = deleteWine
exports.deleteFromCave = deleteFromCave
exports.deleteMany = deleteMany
exports.addToCave = addToCave
exports.list = list
exports.rate = rate
exports.find = find
exports.update = update
